version: '3'
services:
  db_memo:
    image: postgres:latest
    ports:
      - "50001:5432"
    volumes:
      - "./srv/docker/postgres/:/var/lib/postgresql/data"
    env_file: .env

  redis_memo:
    image: redis:alpine
    ports:
      - "50002:6379"
    volumes:
        - "./srv/docker/redis/:/data/"