# Generated by Django 3.2.13 on 2022-06-08 01:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Back')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('front', models.CharField(max_length=255, verbose_name='Front')),
                ('back', models.CharField(max_length=255, verbose_name='Back')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Back')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'Card name must be grater than 2 characters')])),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardAnswerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=255, verbose_name='Answer')),
                ('correct', models.BooleanField(default=True, verbose_name='Correct')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.cardlist'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
