# Generated by Django 4.0.5 on 2022-07-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0005_presetdeck_rename_cardlist_deck_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deck",
            options={"verbose_name": "Deck", "verbose_name_plural": "Decks"},
        ),
        migrations.AlterModelOptions(
            name="presetcard",
            options={
                "verbose_name": "Preset Card",
                "verbose_name_plural": "Preset Cards",
            },
        ),
        migrations.AlterModelOptions(
            name="presetdeck",
            options={
                "verbose_name": "Preset Deck",
                "verbose_name_plural": "Preset Decks",
            },
        ),
        migrations.RemoveField(
            model_name="presetcard",
            name="deck",
        ),
        migrations.AddField(
            model_name="presetcard",
            name="preset_deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preset_cards",
                to="memo.presetdeck",
            ),
            preserve_default=False,
        ),
    ]
