# Generated by Django 4.0.6 on 2022-08-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memo", "0006_alter_deck_options_alter_presetcard_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardanswerhistory",
            name="updated_at",
        ),
    ]
