name: Django CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: github_actions
                    DB_PORT: "5432"
                    DB_HOST: localhost
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready
                    --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.9
              uses: actions/setup-python@v3
              with:
                  python-version: 3.9
            - name: Active Python virtual enviroment
              run: |
                  python -m venv venv
                  . venv/bin/activate
            - name: Install Dependencies
              run: python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run Tests
              env:
                  DEBUG: True
                  HOST_VAR: "http://localhost:8000"
                  SECRET_KEY: "dummy"
                  EMAIL_PASSWORD: "${{ secrets.EMAIL_PASSWORD }}"
                  EMAIL_USER: "${{ secrets.EMAIL_USER }}"
                  REDIS_URL: "${{ secrets.REDIS_URL }}"
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: postgres
                  POSTGRES_DB: github_actions
                  DB_PORT: "5432"
                  DB_HOST: localhost
              run: |
                  python manage.py collectstatic
                  pytest
